### ISSUE TITLE
 `module` directive missing.

### ISSUE THREAD

**Issue by labyrwa** [openscholar/starterkit#2]
When adding the .zip of my flavor OS is giving me an error that 'module' directive is missing. Any ideas?

**Comment by rsasch** [comment]
The way around that (it's a known bug) is to — instead of zipping the folder that contains your theme — go inside that folder, select the files/folders within, and add those to a zip archive.  On the Mac, that would look like this
![archive](https://cloud.githubusercontent.com/assets/1713505/6491462/4d723280-c27b-11e4-8291-01823ae26d01.png)

**Comment by labyrwa** [comment]
Perfect, thanks for that. Closing
